// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HandleGetGPMs() {
  return window['go']['main']['App']['HandleGetGPMs']();
}

export function HandleInsertGPM(arg1) {
  return window['go']['main']['App']['HandleInsertGPM'](arg1);
}
